name: CI

on: push

jobs:
  install:
    name: Install Tools

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v1

      - name: help
        run: bash ./bootstrap.sh -h
      - name: cmake
        run: bash ./bootstrap.sh cmake
      - name: terminal
        run: bash ./bootstrap.sh terminal
      - name: ros
        run: bash ./bootstrap.sh ros